Card_Number = input("Enter your credit card number")
Expiration_Date = input("Enter your credit card Expiration Date")
CCV = input("Enter your CCV")
print(f'Your credit card number is {Card_Number}')
print(f'Your expiration date is {Expiration_Date}') 
print(f'Your CCV is {CCV}')